# -*- coding: utf-8 -*-
"""exPy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgQfHsGtHsZGfE4xXRBBlwJq_MClVsh0
"""

#Fatores em P
#Crie um vetor de categorias com cores vermelho, azul e verde
import pandas as pd
cores = pd.Categorical(['vermelho', 'azul', 'verde'])
print(cores)

#Crie um vetor de fatores para os dias da semana e imprima-os
import pandas as pd
semana = pd.Categorical(['segunda', 'terca', 'quarta', 'quinta', 'sexta'])
print(semana)

#ex médio: crie um vetor de fatores com as categoarias "baixo", "medio" e "alto" e ordene-os
import pandas as pd
categorias = pd.Categorical(['baixo', 'medio', 'alto'], categories = ['baixo', 'medio', 'alto'], ordered = True)
print(categorias)

#converta um vetor de fatores em vetores numericos
import pandas as pd
categorias = pd.Categorical(['baixo', 'medio', 'alto'], categories = ['baixo', 'alto', 'medio'], ordered = True)
print(categorias.codes)

#Crie um vetor de fatoes com as categorias "Pequeno", "medio", "Grande" e substirus o "pequeno" por "extra pequeno"
import pandas as pd
tamanho = pd.Categorical(['pequeno', 'medio', 'grande'], categories = ['pequeno', 'medio', 'grande'], ordered = True)
tamanho2 = tamanho.rename_categories({"pequeno":"extra-pequeno"})
print(tamanho2)

#criei um vetor de fatorees com 100 elementos aleatorios enttre "baixo", "medio" e "alto", calcule a frequencia de cada categoria
import pandas as pd
import random
categorias = ["baixo", "medio", "alto"]
vetor = [random.choice(categorias) for i in range(100)]
fatores = pd.Categorical(vetor, categories = categorias, ordered = True)
frequencia = pd.value_counts(fatores)
print(frequencia)

#crie uma lista contendo numeros de 1 a 5
import numpy as pd
lista = pd.array([1,2,3,4,5])
print(lista)

#crie uma lista contendo numeros de 1 a 5 e adicione o 6
import numpy as pd
lista = pd.array([1,2,3,4,5])
lista2 = pd.append(lista, 6)
print(f"lista: {lista}")
print(f"lista com adição: {lista2}")

#crie uma lista contendo numeros de 1 a 5 e remova 3 posição
lista = [1,2,3,4,5]
lista.pop(2)
print(f"lista: {lista}")

#inverta a ordem dos elemntos da lista
lista = [1,2,3,4,5]
lista.reverse()
print(f"lista: {lista}")

#crie uma lista de lista - matriz
matriz = [[1,2,3], [4,5,6], [7,8,9]]
somaM = [sum(linha) for linha in matriz]
print(f"soma de cada linha: {somaM}")

# crie uma tupla com numeros de 1 a 5

tupla = (1,2,3,4,5)
print(tupla)

# crie uma tupla com numeros de 1 a 5 e imprima 0 terceiro

tupla = (1,2,3,4,5)
print(tupla[2])

#crie uma tupla com outras treis tuplas interna, cada uma com dois elementos
tupla = ((1,2), (3,4), (5,6))
print(tupla)

#concatene duas tuplas e imprima
tupla1 = (1,2,3)
tupla2 = (4,5,6)
tupla3 = tupla1 + tupla2
print(tupla3)

#crie uma tupla com os elementos (1,2,3,4,5) e verifique o numero 3 esta na lista
tupla = (1,2,3,4,5)
if 3 in tupla:
    print("3 esta na lista")
else :
    print("3 não esta na lista")

#outro jeito
existe = 3 in tupla
print(existe)

#crie uma tupla com os elementos (1,2,3,4,5) e verifique o indice 4  na lista
tupla = (1,2,3,4,5)
print(tupla.index(4))

#crie um dicionario com as chaves "nome", "idade" e "cidade"
dicionario = {"nome": "joao", "idade": 30, "cidade": "são paulo"}
print(dicionario)

#crie um dicionario com as chaves "nome", "idade" e "cidade" e acesse idade
dicionario = {"nome": "joao", "idade": 30, "cidade": "são paulo"}
print(dicionario["idade"])

#adicione um par de chave-valor "profissão": engenharia ao dicionario = {"nome": "joao", "idade": 30, "cidade": "são paulo"}

dicionario = {"nome": "joao", "idade": 30, "cidade": "são paulo"}
dicionario["profissão"] = "engenharia"
print(dicionario)